# 対義語
antonyms:
  - ["酷似（こくじ）", "近似（きんじ）"]
  - ["醜悪（しゅうあく）", "美麗（びれい）"]
  - ["予鈴（よれい）", "本鈴（ほんれい）"]
  - ["剛健（ごうけん）", "柔弱（にゅうじゃく）"]
  - ["過剰（かじょう）", "不足（ふそく）"]
  - ["駄作（ださく）", "秀作（しゅうさく）"]
  - ["駄作（ださく）", "傑作（けっさく）"]
  - ["私邸（してい）", "官邸（かんてい）"]
  - ["私邸（してい）", "公邸（こうてい）"]
  - ["頑健（がんけん）", "虚弱（きょじゃく）"]
  - ["顕著（けんちょ）", "隠微（いんび）"]
  - ["享楽（きょうらく）", "禁欲（きんよく）"]
  - ["亭主（ていしゅ）", "妻女（さいじょ）"]
  - ["反歌（はんか）", "長歌（ちょうか）"]

# 同音異義語
homonym:
  - ["こくじ", "酷似", "告示", "告辞", "国字", "国事", "刻時"]
  - ["しゃくりょう", "酌量", "借料"]
  - ["おうしゅう", "応酬", "押収", "欧州", "奥州"]
  - ["じょうせい", "醸成", "情勢", "状勢", "上声"]
  - ["じゅうだん", "銃弾", "縦断", "十段"]
  - ["じょうほう", "銃砲", "什宝", "重宝"]
  - ["せんてつ", "銑鉄", "先哲"]
  - ["ちょうか", "釣果", "超過"]
  - ["いはつ", "衣鉢", "遺髪"]
  - ["かんめい", "感銘", "肝銘", "簡明", "官命"]
  - ["よれい", "予鈴", "余齢"]
  - ["きが", "飢餓", "起臥", "帰臥"]
  - ["せいか", "製靴", "生花", "盛夏", "正価", "製菓", "成果", "青果", "生家", "聖火", "聖歌"]
  - ["ごうけん", "剛健", "合憲"]
  - ["こんごう", "金剛", "混合", "根号"]
  - ["かじょう", "過剰", "箇条"]
  - ["よじょう", "余剰", "余情", "四畳"]
  - ["かいぼう", "解剖", "海防"]
  - ["だんがい", "弾劾", "断崖"]
  - ["ちょくし", "勅使", "直視", "勅旨"]
  - ["けんしょう", "顕彰", "検証", "健勝", "懸賞", "憲章"]
  - ["ひょうしょう", "表彰", "表象"]
  - ["してい", "私邸", "指定", "師弟", "子弟", "姉弟"]
  - ["らっかん", "落款", "楽観"]
  - ["こうかく", "甲殻", "口角", "降格", "広角"]
  - ["ちかく", "地殻", "知覚"]
  - ["がんけん", "頑健", "眼瞼"]
  - ["はんか", "頒価", "反歌", "繁華"]
  - ["はんぷ", "頒布", "帆布"]
  - ["きょうじゅ", "享受", "教授"]
  - ["きょうらく", "享楽", "京楽"]

# 類義語
synonyms:
  - ["残酷（ざんこく）", "残虐（ざんぎゃく）", "残忍（ざんにん）"]
  - ["酌量（しゃくりょう）", "斟酌（しんしゃく）", "考慮（こうりょ）"]
  - ["応酬（おうしゅう）", "やりとり（やりとり）"]
  - ["報酬（ほうしゅう）", "対価（たいか）"]
  - ["醜悪（しゅうあく）", "グロテスク（グロテスク）"]
  - ["醸成（じょうせい）", "醸造（じょうぞう）"]
  - ["酪農（らくのう）", "畜産（ちくさん）"]
  - ["銃弾（じゅうだん）", "鉄砲玉（てっぽうだま）", "砲弾（ほうだん）"]
  - ["銑鉄（せんてつ）", "高炭素鉄（こうたんそてつ）"]
  - ["釣り（つり）", "魚釣り（さかなつり）", "釣魚（ちょうぎょ）", "釣り銭（つりせん）"]
  - ["火鉢（ひばち）", "火桶（ひおけ）", "火櫃（ひびつ）"]
  - ["銘柄（めいがら）", "商標（しょうひょう）", "商品名（しょうひんめい）"]
  - ["飢餓（きが）", "飢え（うえ）", "空腹（くうふく）"]
  - ["靴下（くつした）", "ストッキング（ストッキング）", "ソックス（ソックス）"]
  - ["駄作（ださく）", "愚作（ぐさく）"]
  - ["無駄（むだ）", "従（いたずら）", "余計（よけい）", "無用（むよう）"]
  - ["金剛（こんごう）", "ダイヤモンド（ダイヤモンド）"]
  - ["余剰（よじょう）", "剰余（じょうよ）"]
  - ["解剖（かいぼう）", "解体（かいたい）", "腑分け（ふわけ）"]
  - ["勅命（ちょくめい）", "詔（みことのり）"]
  - ["借款（しゃっかん）", "会社の借金（かいしゃのしゃっきん）"]
  - ["頻繁（ひんぱん）", "頻頻繋ぐ（しくしくつなぐ）", "頻々繋ぐ（しくしくつなぐ）"]
  - ["頑固（がんこ）", "強情（ごうじょう）"]
  - ["顕著（けんちょ）", "歴然（れきぜん）"]
  - ["頒価（はんか）", "頒布価格（はんぷかかく）"]
  - ["頒布（はんぷ）", "配布（はいふ）"]
  - ["亭主（ていしゅ）", "主人（しゅじん）", "夫（おっと）"]

# 参照
confer:
  - ["残酷（ざんこく）", "残酷非道（ざんこくひどう）"]
  - ["美醜（びしゅう）", "善悪美醜（ぜんあくびしゅう）"]
  - ["火鉢（ひばち）", "火鉢にあたる（ひばちにあたる）"]
  - ["衣鉢（いはつ）", "衣鉢を継ぐ（いはつをつぐ）", "袈裟と鉢（けさとはち）"]
  - ["金剛（こんごう）", "金剛石（こんごうせき）", "ダイヤモンド（ダイヤモンド）"]
  - ["過剰（かじょう）", "過剰防衛（かじょうぼうえい）", "過剰反応（かじょうはんのう）"]
  - ["弾劾（だんがい）", "弾劾裁判（だんがいさいばん）"]
  - ["勅旨（ちょくし）", "勅旨を伝える使者（ちょくしをつたえるししゃ）"]
  - ["表彰（ひょうしょう）", "表彰台（ひょうしょうだい）", "表彰状（ひょうしょうじょう）"]
  - ["邸宅（ていたく）", "屋敷（やしき）", "大住宅（だいじゅうたく）"]
  - ["口角（こうかく）", "口角泡を飛ばす（こうかくあわをとばす）"]
  - ["頻発（ひんぱつ）", "しきりに発生すること（しきりにはっせいすること）"]
  - ["頻繁（ひんぱん）", "頻繁に（ひんぱんに）", "頻頻と（しくしくと）", "頻々と（しくしくと）"]
  - ["亭主（ていしゅ）", "亭主八盃（ていしゅはっぱい）"]
  - ["料亭（りょうてい）", "日本料理の高級料理屋（にほんりょうりのこうきゅうりょうりや）"]

# 四字熟語
four:
  - ["酌量（しゃくりょう）", "情状酌量（じょうじょうしゃくりょう）", "酌量減軽（しゃくりょうげんけい）"]
  - ["剛健（ごうけん）", "質実剛健（しつじつごうけん）"]
  - ["頑固（がんこ）", "頑迷固陋（がんめいころう）", "頑固一徹（がんこいってつ）"]

