# 対義語
antonyms:
  - ["酷似（こくじ）", "近似（きんじ）"]
  - ["醜悪（しゅうあく）", "美麗（びれい）"]
  - ["予鈴（よれい）", "本鈴（ほんれい）"]
  - ["剛健（ごうけん）", "柔弱（にゅうじゃく）"]
  - ["過剰（かじょう）", "不足（ふそく）"]
  - ["駄作（ださく）", "秀作（しゅうさく）", "傑作（けっさく）"]
  - ["私邸（してい）", "官邸（かんてい）", "公邸（こうてい）"]
  - ["頑健（がんけん）", "虚弱（きょじゃく）"]
  - ["顕著（けんちょ）", "隠微（いんび）"]
  - ["享楽（きょうらく）", "禁欲（きんよく）"]
  - ["亭主（ていしゅ）", "妻女（さいじょ）"]
  - ["反歌（はんか）", "長歌（ちょうか）"]

# 同音異義語
homonym:
  - ["こくじ", "酷似", "告示", "告辞", "国字", "国事", "刻時"]
  - ["しゃくりょう", "酌量", "借料"]
  - ["おうしゅう", "応酬", "押収", "欧州", "奥州"]
  - ["じょうせい", "醸成", "情勢", "状勢", "上声"]
  - ["じゅうだん", "銃弾", "縦断", "十段"]
  - ["じょうほう", "銃砲", "什宝", "重宝"]
  - ["せんてつ", "銑鉄", "先哲"]
  - ["ちょうか", "釣果", "超過"]
  - ["いはつ", "衣鉢", "遺髪"]
  - ["かんめい", "感銘", "肝銘", "簡明", "官命"]
  - ["よれい", "予鈴", "余齢"]
  - ["きが", "飢餓", "起臥", "帰臥"]
  - ["せいか", "製靴", "生花", "盛夏", "正価", "製菓", "成果", "青果", "生家", "聖火", "聖歌"]
  - ["ごうけん", "剛健", "合憲"]
  - ["こんごう", "金剛", "混合", "根号"]
  - ["かじょう", "過剰", "箇条"]
  - ["よじょう", "余剰", "余情", "四畳"]
  - ["かいぼう", "解剖", "海防"]
  - ["だんがい", "弾劾", "断崖"]
  - ["ちょくし", "勅使", "直視", "勅旨"]
  - ["けんしょう", "顕彰", "検証", "健勝", "懸賞", "憲章"]
  - ["ひょうしょう", "表彰", "表象"]
  - ["してい", "私邸", "指定", "師弟", "子弟", "姉弟"]
  - ["らっかん", "落款", "楽観"]
  - ["こうかく", "甲殻", "口角", "降格", "広角"]
  - ["ちかく", "地殻", "知覚"]
  - ["がんけん", "頑健", "眼瞼"]
  - ["はんか", "頒価", "反歌", "繁華"]
  - ["はんぷ", "頒布", "帆布"]
  - ["きょうじゅ", "享受", "教授"]
  - ["きょうらく", "享楽", "京楽"]

# 類義語
synonyms:
  - ["残酷（ざんこく）", "残虐（ざんぎゃく）", "残忍（ざんにん）"]
  - ["酌量（しゃくりょう）", "斟酌（しんしゃく）", "考慮（こうりょ）"]

# 参照
confer:
  - ["残酷（ざんこく）", "残酷非道（ざんこくひどう）"]
  - ["美醜（びしゅう）", "善悪美醜（ぜんあくびしゅう）"]

# 四字熟語
four:
  - ["酌量（しゃくりょう）", "情状酌量（じょうじょうしゃくりょう）", "酌量減軽（しゃくりょうげんけい）"]
  - ["剛健（ごうけん）", "質実剛健（しつじつごうけん）"]
