# 対義語
antonyms:
  - ["酷似（こくじ）", "近似（きんじ）"]
  - ["醜悪（しゅうあく）", "美麗（びれい）"]

# 同音異義語
homonym:
  - ["酷似（こくじ）", "告示", "告辞", "国字", "国事", "刻時"]
  - ["酌量（しゃくりょう）", "借料"]

# 類義語
synonyms:
  - ["残酷（ざんこく）", "残虐（ざんぎゃく）", "残忍（ざんにん）"]
  - ["酌量（しゃくりょう）", "斟酌（しんしゃく）", "考慮（こうりょ）"]

# 参照
confer:
  - ["残酷（ざんこく）", "残酷非道（ざんこくひどう）"]
  - ["美醜（びしゅう）", "善悪美醜（ぜんあくびしゅう）"]

# 四字熟語
four:
  - ["酌量（しゃくりょう）", "情状酌量（じょうじょうしゃくりょう）", "酌量減軽（しゃくりょうげんけい）"]
  - ["剛健（ごうけん）", "質実剛健（しつじつごうけん）"]
