# 対義語
antonyms:
  - ["酷似（こくじ）", "近似（きんじ）"]
  - ["醜悪（しゅうあく）", "美麗（びれい）"]
  - ["予鈴（よれい）", "本鈴（ほんれい）"]
  - ["剛健（ごうけん）", "柔弱（にゅうじゃく）"]
  - ["過剰（かじょう）", "不足（ふそく）"]
  - ["駄作（ださく）", "秀作（しゅうさく）", "傑作（けっさく）"]
  - ["私邸（してい）", "官邸（かんてい）", "公邸（こうてい）"]
  - ["頑健（がんけん）", "虚弱（きょじゃく）"]
  - ["顕著（けんちょ）", "隠微（いんび）"]
  - ["享楽（きょうらく）", "禁欲（きんよく）"]
  - ["亭主（ていしゅ）", "妻女（さいじょ）"]
  - ["反歌（はんか）", "長歌（ちょうか）"]

# 同音異義語
homonym:
  - ["酷似（こくじ）", "告示", "告辞", "国字", "国事", "刻時"]
  - ["酌量（しゃくりょう）", "借料"]
  - ["応酬（おうしゅう）", "押収", "欧州", "奥州"]
  - ["醸成（じょうせい）", "情勢", "状勢", "上声"]
  - ["銃弾（じゅうだん）", "縦断", "十段"]
  - ["銃砲（じゅうほう）", "什宝", "重宝"]
  - ["銑鉄（せんてつ）", "先哲"]
  - ["釣果（ちょうか）", "超過"]
  - ["衣鉢（いはつ）", "遺髪"]
  - ["感銘（かんめい）", "肝銘", "簡明", "官命"]
  - ["予鈴（よれい）", "余齢"]
  - ["飢餓（きが）", "起臥", "帰臥"]
  - ["製靴（せいか）", "生花", "盛夏", "正価", "製菓", "成果", "青果", "生家", "聖火", "聖歌"]
  - ["剛健（ごうけん）", "合憲"]
  - ["金剛（こんごう）", "混合", "根号"]
  - ["過剰（かじょう）", "箇条"]
  - ["余剰（よじょう）", "余情", "四畳"]
  - ["解剖（かいぼう）", "海防"]
  - ["弾劾（だんがい）", "断崖"]
  - ["勅使（ちょくし）", "直視", "勅旨"]
  - ["顕彰（けんしょう）", "検証", "健勝", "懸賞", "憲章"]
  - ["表彰（ひょうしょう）", "表象"]
  - ["私邸（してい）", "指定", "師弟", "子弟", "姉弟"]
  - ["落款（らっかん）", "楽観"]
  - ["甲殻（こうかく）", "口角", "降格", "広角"]
  - ["地殻（ちかく）", "知覚"]
  - ["頑健（がんけん）", "眼瞼"]
  - ["頒価（はんか）", "反歌", "繁華"]
  - ["頒布（はんぷ）", "帆布"]
  - ["享受（きょうじゅ）", "教授"]
  - ["享楽（きょうらく）", "京楽"]

# 類義語
synonyms:
  - ["残酷（ざんこく）", "残虐（ざんぎゃく）", "残忍（ざんにん）"]
  - ["酌量（しゃくりょう）", "斟酌（しんしゃく）", "考慮（こうりょ）"]

# 参照
confer:
  - ["残酷（ざんこく）", "残酷非道（ざんこくひどう）"]
  - ["美醜（びしゅう）", "善悪美醜（ぜんあくびしゅう）"]

# 四字熟語
four:
  - ["酌量（しゃくりょう）", "情状酌量（じょうじょうしゃくりょう）", "酌量減軽（しゃくりょうげんけい）"]
  - ["剛健（ごうけん）", "質実剛健（しつじつごうけん）"]
