# 対義語
antonyms:
  - ["寡黙（かもく）", "饒舌[冗舌]（じょうぜつ）"]
  - ["寛大（かんだい）", "厳格（げんかく）"]
  - ["寛容（かんよう）", "狭量（きょうりょう）"]
  - ["春宵（しゅんしょう）", "秋宵（しゅうしょう）"]
  - ["丁寧（ていねい）", "ぞんざい（ぞんざい）"]
  - ["丁寧（ていねい）", "いい加減（いいかげん）"]
  - ["自薦（じせん）", "他薦（たせん）"]
  - ["別荘（べっそう）", "本邸（ほんてい）"]
  - ["扉（とびら）", "引き戸（ひきど）"]
  - ["扉（とびら）", "奥付（おくづけ）"]
  - ["窃取（せっしゅ）", "強奪（ごうだつ）"]
  - ["窃盗（せっとう）", "強盗（ごうとう）"]
  - ["充実（じゅうじつ）", "空虚（くうきょ）"]
  - ["泰然自若（たいぜんじじゃく）", "戦々恐々（せんせんきょうきょう）"]

# 同音異義語
homonym:
  - ["かもく", "寡黙", "科目", "課目"]
  - ["しゅうか", "衆寡", "集荷", "秀歌"]
  - ["かんよう", "寛容", "観葉", "涵養", "慣用", "肝要"]
  - ["さいしょう", "宰相", "最少", "最小"]
  - ["しゅさい", "主宰", "主催", "主菜"]
  - ["りょうせい", "良性", "両性", "両生", "両棲"]
  - ["りょうぼ", "寮母", "陵墓"]
  - ["さいきん", "細菌", "最近"]
  - ["きゅうけい", "球茎", "球形", "休憩", "求刑", "急啓"]
  - ["かいそう", "海藻", "階層", "海草", "改装", "回想"]
  - ["しそう", "詞藻", "死相", "思想", "試走", "歯槽"]
  - ["へんれい", "返戻", "返礼"]
  - ["せっしゅ", "窃取", "接種", "摂取"]
  - ["せっとう", "窃盗", "接頭"]
  - ["すいとう", "水筒", "出納", "水稲", "水痘"]
  - ["ふうとう", "封筒", "風濤"]
  - ["りょしゅう", "虜囚", "旅愁"]
  - ["そうがい", "霜害", "窓外"]
  - ["たいぜん", "泰然", "大全"]
  - ["ごへい", "語弊", "御幣"]

# 類義語
synonyms:
  - ["寡黙（かもく）", "無口（むくち）"]
  - ["寛大（かんだい）", "寛容（かんよう）"]
  - ["適宜（てきぎ）", "適当（てきとう）", "随意（ずいい）"]
  - ["宰相（さいしょう）", "首相（しゅしょう）", "総理大臣（そうりだいじん）"]
  - ["安寧（あんねい）", "平和（へいわ）", "安泰（あんたい）", "安定（あんてい）", "平穏無事（へいおんぶじ）"]
  - ["丁寧（ていねい）", "念入り（ねんいり）"]
  - ["寮生（りょうせい）", "寄宿生（きしゅくせい）"]
  - ["細菌（さいきん）", "バクテリア（ばくてりあ）"]
  - ["殺菌（さっきん）", "滅菌（めっきん）", "消毒（しょうどく）"]
  - ["薫風（くんぷう）", "南風（みなみかぜ）"]
  - ["歯茎（はぐき）", "歯肉（しにく）"]
  - ["自薦（しぜん）", "自選（じせん）"]
  - ["推薦（すいせん）", "推挙（すいきょ）"]
  - ["別荘（べっそう）", "別邸（べってい）", "別宅（べったく）"]
  - ["扉（とびら）", "引き戸（ひきど）"]
  - ["返戻（へんれい）", "還付（かんぷ）", "返却（へんきゃく）", "返済（へんさい）", "返還（へんかん）"]
  - ["困窮（こんきゅう）", "辛酸（しんさん）", "貧窮（ひんきゅう）"]
  - ["窃取（せっしゅ）", "窃盗（せっとう）"]
  - ["罷業（ひぎょう）", "ストライキ（すとらいき）"]
  - ["罷免（ひめん）", "解雇（かいこ）", "免職（めんしょく）", "解任（かいにん）", "パージ（ぱーじ）"]
  - ["虜囚（りょしゅう）", "捕虜（ほりょ）", "擒（とりこ）"]
  - ["捕虜（ほりょ）", "俘虜（ふりょ）", "とりこ（とりこ）"]
  - ["雰囲気（ふんいき）", "気分（きぶん）", "情調（じょうちょう）"]
  - ["補充（ほじゅう）", "補填（ほてん）", "補足（ほそく）"]
  - ["安泰（あんたい）", "無事（ぶじ）", "平穏（へいおん）", "安寧（あんねい）"]
  - ["弊害（へいがい）", "害悪（がいあく）"]

# 参照
confer:
  - ["衆寡（しゅうか）", "多数と少数（たすうとしょうすう）"]
  - ["寛大（かんだい）", "大目に見る（おおめにみる）"]
  - ["便宜（べんぎ）", "便宜を図る（べんぎをはかる）"]
  - ["春宵（しゅんしょう）", "春宵一刻値千金（しゅんしょういっこくあたいせんきん）"]
  - ["宵（よい）", "宵の口（よいのくち）", "宵の明星（よいのみょうじょう）"]
  - ["丁寧（ていねい）", "懇切丁寧（こんせつていねい）"]
  - ["細菌（さいきん）", "ウイルス（ういるす）"]
  - ["薫陶（くんとう）", "師の薫陶を受ける（しのくんとうをうける）"]
  - ["薫風（くんぷう）", "初夏の風（しょかのかぜ）", "風薫る（かぜかおる）"]
  - ["球茎（きゅうけい）", "クワイ（くわい）", "地下茎（ちかけい）"]
  - ["自薦（じせん）", "自己推薦（じこすいせん）", "他己推薦（たこすいせん）"]
  - ["門扉（もんぴ）", "門扉を閉ざす（もんぴをとざす）"]
  - ["戻す（もどす）", "縒りを戻す（よりをもどす）"]
  - ["爵位（しゃくい）", "貴族の称号（きぞくのしょうごう）", "爵位と位階（しゃくいといかい）"]
  - ["伯爵（はくしゃく）", "五等爵（ごとうしゃく）"]
  - ["窮屈（きゅうくつ）", "堅苦しい（かたくるしい）"]
  - ["困窮（こんきゅう）", "困窮疲労（こんきゅうひろう）", "困窮疲弊（こんきゅうひへい）"]
  - ["窯業（ようぎょう）", "陶磁器（とうじき）", "ガラス（がらす）", "セメントを作る職業（せめんとをつくるしょくぎょう）"]
  - ["窯元（かまもと）", "陶磁器の製造元（とうじきのせいぞうもと）"]
  - ["罷業（ひぎょう）", "同盟罷業（どうめいひぎょう）"]
  - ["羅列（られつ）", "思いつくがまま並べること（おもいつくがままならべること）"]
  - ["網羅（もうら）", "魚をとる網と鳥をとる網の両方（さかなをとるあみととりをとるあみのりょうほう）"]
  - ["虞（おそれ）", "恐れ（おそれ）", "怖れ（おそれ）", "畏れ（おそれ）"]
  - ["虜囚（りょしゅう）", "恋のとりことなる（こいのとりことなる）"]
  - ["霜害（そうがい）", "早霜（はやじも）", "遅霜（おそじも）", "晩霜（ばんそう）"]
  - ["初霜（はつしも）", "初霜月（はつしもづき）"]
  - ["語弊（ごへい）", "誤解を招きやすい言い方（ごかいをまねきやすいいいかた）"]

# 四字熟語
four:
  - ["荘厳（そうごん）", "荘厳華麗（そうごんかれい）", "荘厳美麗（そうごんびれい）"]
  - ["泰然（たいぜん）", "泰然自若（たいぜんじじゃく）"]
